### ISSUE TITLE
data-revolution

### ISSUE THREAD

**Issue by xriss** [devinit/digital-platform#238]
can we go with colour instead of color for the header of the various csv files

id,colour,detail,source-title,source-link

and can we go with a type of colour instead of simple in the 3rd colum of concepts.csv file for this format of data, eg

country-year,educ-mis,colour,,Education management information system,"id, color, detail, source-title, source-link","A national administrative system recording data from all education facilities on staff, logistics, performance etc",lin,data-revolution,data-revolution,8,,,,UNICEF Country Annual Reports. Link: www.unicef.org/about/annualreport/index_82089.html  UIS Data Quality Assessment Framework (DQAF) output. Link: www.poledakar.com/dqaf/index.php?title=DQAF_Events,,,,,,,,"A national administrative system recording data from all education facilities on staff, logistics, performance etc",Education management information system (Africa only),www.unicef.org/about/annualreport/index_82089.html; www.poledakar.com/dqaf/index.php?title=DQAF_Events,,

and of course if you add the data-revolution theme it should begin to work in the test builds.

**Comment by dw8547** [comment]
Dead issue?
