### ISSUE TITLE
Outward FDI

### ISSUE THREAD

**Issue by Duncan-Knox** [devinit/digital-platform#240]
An error in the excel file used for international resources > inflows vs outflows with FDI outflows (Outflow of profits on FDI and outward investment) has cropped up again as I think this was fixed after it was uploaded from excel last time, and has therefore gone through again as the excel file has been uploaded.

The error is, outward investment is adding outflow of profits on FDI to its total. E.g. Bangladesh, outward investment is 1.85bn and outflow of profits on FDI is 1.82bn. Fixed outward investment would be 0.03bn and outflow of profits on FDI would remain at 1.82bn.

**Comment by dw8547** [comment]
Dead issue?
