### ISSUE TITLE
l4 colum removed from domestic.csv

### ISSUE THREAD

**Issue by xriss** [devinit/digital-platform#242]
@akmiller01  I just tracked down a bug in the di-website to the fact that the l4 column has been removed from domestic.csv in the development branch.

Should I fix di-website to cope with this or is this a problem with the data?

https://github.com/devinit/digital-platform/blob/development/country-year/domestic.csv

**Comment by akmiller01** [comment]
That was unintentional... I thought I fixed it in both Master and Development, but try copying over the Master branch.

-Alex

**Comment by xriss** [comment]
Ah yes, thanx, Merging in the master fixes it. I just wasn't sure which side needed fixing the digital-platform or di-website.
