### ISSUE TITLE
Data warehouse check, oda.csv/fact.oda

### ISSUE THREAD

**Issue by xriss** [devinit/digital-platform#243]
I've added a warehouse branch containing data that has been imported from Data Warehouse as a test. Please check that they are ok.

https://github.com/devinit/digital-platform/tree/warehouse

Mostly I think the import has had a slight cosmetic effect on the format of the CSV files, ie numerical formats or use of quotes or line endings.

The most important part of the CSV files are the header names so double check that these are still the same.

Note that not all files have been imported, for instance I've ignored all files under the reference directory and the following files have not been changed as I'm not sure where to get the data from.

country-year/adult-literacy
country-year/domestic-netlending
country-year/education-pc-transferred-oda
country-year/employment-agriculture
country-year/employment-by-sector
country-year/employment-industry
country-year/employment-services
country-year/gdp-current-ncu-fy
country-year/gdp-growth
country-year/gdp-pc-usd-2005
country-year/gdp-pc-usd-current
country-year/gdp-usd-2005
country-year/gdp-usd-2012
country-year/gni-usd-2005
country-year/govtspend-USD
country-year/health-pc-transferred-oda
country-year/income-share-top-10pc
country-year/infant-mortality
country-year/in-oda-and-repayments
country-year/in-oof-and-repayments
country-year/in-oof-net
country-year/intl-flows-donors-wide
country-year/intl-flows-recipients-wide
country-year/kenya-electricity-avg
country-year/kenya-electricity-rank
country-year/kenya-improved-sani-avg
country-year/kenya-improved-sani-rank
country-year/kenya-improved-water-avg
country-year/kenya-improved-water-rank
country-year/kenya-paved-roads-avg
country-year/kenya-paved-roads-rank
country-year/kenya-pov-avg
country-year/kenya-pov-rank
country-year/kenya-urban-avg
country-year/kenya-urban-rank
country-year/long-term-debt
country-year/mean-years-of-schooling
country-year/non-grant-revenue-PPP-capita
country-year/oda
country-year/oda-donor/oda-AE
country-year/oda-donor/oda-afdb
country-year/oda-donor/oda-afdf
country-year/oda-donor/oda-afesd
country-year/oda-donor/oda-arab-fund-afesd
country-year/oda-donor/oda-asdb-special-funds
country-year/oda-donor/oda-AT
country-year/oda-donor/oda-AU
country-year/oda-donor/oda-badea
country-year/oda-donor/oda-BE
country-year/oda-donor/oda-CA
country-year/oda-donor/oda-CH
country-year/oda-donor/oda-CZ
country-year/oda-donor/oda-DE
country-year/oda-donor/oda-DK
country-year/oda-donor/oda-ebrd
country-year/oda-donor/oda-EE
country-year/oda-donor/oda-ES
country-year/oda-donor/oda-EU
country-year/oda-donor/oda-FI
country-year/oda-donor/oda-FR
country-year/oda-donor/oda-gavi
country-year/oda-donor/oda-GB
country-year/oda-donor/oda-gef
country-year/oda-donor/oda-global-fund
country-year/oda-donor/oda-GR
country-year/oda-donor/oda-ibrd
country-year/oda-donor/oda-ida
country-year/oda-donor/oda-idb-specialfund
country-year/oda-donor/oda-IE
country-year/oda-donor/oda-ifad
country-year/oda-donor/oda-imf
country-year/oda-donor/oda-imf-concessional-trust-fund
country-year/oda-donor/oda-IS
country-year/oda-donor/oda-islamic-dev-bank
country-year/oda-donor/oda-IT
country-year/oda-donor/oda-JP
country-year/oda-donor/oda-KR
country-year/oda-donor/oda-KW
country-year/oda-donor/oda-LU
country-year/oda-donor/oda-NL
country-year/oda-donor/oda-NO
country-year/oda-donor/oda-nordic-dev-fund
country-year/oda-donor/oda-NZ
country-year/oda-donor/oda-ofid
country-year/oda-donor/oda-osce
country-year/oda-donor/oda-PL
country-year/oda-donor/oda-PT
country-year/oda-donor/oda-SE
country-year/oda-donor/oda-SI
country-year/oda-donor/oda-SK
country-year/oda-donor/oda-unaids
country-year/oda-donor/oda-undp
country-year/oda-donor/oda-unece
country-year/oda-donor/oda-unfpa
country-year/oda-donor/oda-unhcr
country-year/oda-donor/oda-unicef
country-year/oda-donor/oda-unpbf
country-year/oda-donor/oda-unrwa
country-year/oda-donor/oda-US
country-year/oda-donor/oda-wfp
country-year/oda-donor/oda-who
country-year/out-oda-and-repayments
country-year/out-oda-gross
country-year/out-oof-and-repayments
country-year/out-oof-gross
country-year/poorest20pct-percentages
country-year/population-0-14
country-year/population-15-64
country-year/population-65-
country-year/poverty-gap-125
country-year/poverty-gap-2
country-year/primary-school-enrolment
country-year/taxrev-pctGDP
country-year/total-employment
country-year/total-revenue-pct-GDP
country-year/total-revenue-PPP-capita
country-year/under-5-mortality
country-year/university-college-enrolment
country-year/youth-literacy
country-year/youth-unemployment

**Comment by xriss** [comment]
BTW I haven't included the oda.csv as although I have set it up to download and it seems like the right data. (although its header names are slightly wrong.)

remote: error: File country-year/oda.csv is 185.02 MB; this exceeds GitHub's file size limit of 100.00 MB

it's somewhat larger than the one we currently have so I cant push it to you here to check out. You could try running the import yourself to check it is valid?

**Comment by dw8547** [comment]
@xriss, re: "The most important part of the CSV files are the header names so double check that these are still the same."

Could you please **confirm if the name of the table in ddw must match the name of the .csv file as on https://github.com/devinit/digital-platform/tree/master/country-year or that the table column names must match the column headers in the .csv files, or both**?

Re: "Note that not all files have been imported, for instance I've ignored all files under the reference directory and the following files have not been changed as I'm not sure where to get the data from."

All of these files: https://github.com/devinit/digital-platform/tree/master/country-year/oda-donor are now in fact.oda_donor &/|| fact.oda_donor_2012. To get https://github.com/devinit/digital-platform/blob/master/country-year/oda-donor/oda-AE.csv for example, we filter fact.oda_donor &/|| fact.oda_donor_2012 on from_di_id = 'AE'. **I'll generate a sample of these to check them as well**.

I've added some background info in: https://github.com/devinit/digital-platform/issues/244.

**Comment by dw8547** [comment]
@xriss & @notshi, @robtew will be helping with the data checking. I'll check the format & @robtew will eyeball the $ values to make sure all is OK. We will only do this for the data series/files/tables that have been automated. They are:

 Schema |              Name              | Type  | Owner  
--------|--------------------------------|-------|--------
 fact   | gdp_usd_current                | table | donata
 fact   | gdp_usd_current_2012           | table | donata
 fact   | gni_pc_usd_current             | table | donata
 fact   | gni_pc_usd_current_2012        | table | donata
 fact   | gni_usd_current                | table | donata
 fact   | gni_usd_current_2012           | table | donata
 fact   | income_share_bottom_20pc       | table | donata
 fact   | income_share_by_quintile       | table | donata
 fact   | income_share_by_quintile_2nd   | table | donata
 fact   | income_share_by_quintile_3rd   | table | donata
 fact   | income_share_by_quintile_4th   | table | donata
 fact   | income_share_by_quintile_5th   | table | donata
 fact   | life_expectancy_at_birth       | table | donata
 fact   | maternal_mortality             | table | donata
 fact   | oda                            | table | donata
 fact   | oda_2012                       | table | donata
 fact   | oda_donor                      | table | donata
 fact   | oda_donor_2012                 | table | donata
 fact   | population_by_age              | table | donata
 fact   | population_by_age_0_14         | table | donata
 fact   | population_by_age_15_64        | table | donata
 fact   | population_by_age_65_and_above | table | donata
 fact   | population_rural               | table | donata
 fact   | population_rural_urban         | table | donata
 fact   | population_total               | table | donata
 fact   | population_urban               | table | donata

We'll start with **ods.csv/oda_2012**.

We'll compare a dump from the fact.oda_2012 table with the oda.csv file downloaded from https://github.com/devinit/digital-platform/blob/master/country-year/oda.csv.

oda.csv was last modified on March 30, 2015 & the OECD have updated the CRS (source) and made revisions to historical data since then, hence the $ values are bound to differ (yes @robtew?). On top of that, aggregation of some non ODA records was recently applied to the CRS and some multilateral donors occasionally replace their data going back 10 years or more. It's unlikely that any rows in the two objects we are comparing will match exactly. @robtew you'll need to make the final call on whether the tables are OK in term of $ content & distribution across sectors/channels/bundles. I'll help @xriss & @notshi to make sure the format is as they need it.

dh = file from here: https://github.com/devinit/digital-platform/tree/master/country-year
ddw = table in ddw 

source | no of unique donors
----------|-----------------------------
dh       | 63
ddw     | 57

The donors missing records in ddw are:

di_id | name                       | donor_code
--------|-----------------------------|-----------------
afesd| Arab Fund [AFESD] | 921
ebrd  |European Bank for Reconstruction and Development [EBRD]|990
ibrd|International Bank for Reconstruction and Development [IBRD]|901
idb-specialfund|IDB Special Fund|912
imf|IMF|907

The **di_id 'afesd' needs to be removed from DH** as it is a **duplicate identifier** of 'arab-fund-afesd' (more details here: https://github.com/devinit/ddw-data/issues/119.

oda_2012 has 780 rows of data against the donor 'arab-fund-afesd' but all $ values are NULL. oda has non NULL $ data for this donor. We've specified in the price conversion function that it should return a NULL value if the divisor is either 0 or NULL. I'm looking into what's happening.

The **di_id 'idb-specialfund' needs to be changed to 'idb-special-fund'** to bring it in line with the di_id naming convention (more details here: https://github.com/devinit/ddw-data/issues/129).

oda_2012 has 3613 rows of data against the donor 'idb-special-fund' but all $ values are NULL. We've specified in the price conversion function that it should return a NULL value if the divisor is either 0 or NULL. I'm looking into what's happening.

This means that donors 'ebrd', 'ibrd', 'imf' are legitimately missing entries in oda_2012. I'm looking into what's  happening.

**Comment by robtew** [comment]
Missing donors are OK - these are due to changes in CRS data between now and when the original downloads were taken last year.

**Comment by dw8547** [comment]
Moving on to recipients in ods.csv/oda_2012.

**Comment by dw8547** [comment]
This is a space holder comment for @robtew to OK the recipients.

**Comment by dw8547** [comment]
Moving on to sectors in ods.csv/oda_2012.

dh = file from here: https://github.com/devinit/digital-platform/tree/master/country-year/oda.csv
ddw = table in ddw 

dh sector | ddw sector
-------------|--------------
agriculture-and-food-security|agriculture & food security
banking-and-business|banking & business
debt-relief|debt relief
education|education
environment|environment
general-budget-support|general budget support
governance-and-security|governance & security
health|health
humanitarian|humanitarian
industry-and-trade|industry & trade
infrastructure|infrastructure
other|other
other-social-services|other social services
water-and-sanitation|water & sanitation

@robtew, **looks OK?**

**Comment by dw8547** [comment]
This is a space holder comment for @robtew to OK the sectors.

**Comment by dw8547** [comment]
Moving on to aid bundle in ods.csv/oda_2012.

dh = file from here: https://github.com/devinit/digital-platform/tree/master/country-year/oda.csv
ddw = table in ddw 

dh bundle | ddw bundle
--------------|----------------
bundle|	bundle
cash-grant	|cash grant
cash-loan-equity	|cash (loan/equity)
commodities-food	|commodities & food
gpgs-nngos	|gpgs & nngos
mixed-project-aid	|mixed project aid
non-transfer	|non-transfer
technical-ooperation	|technical cooperation

@robtew, **looks OK?**

**Comment by dw8547** [comment]
This is a space holder comment for @robtew to OK the aid bundle.

**Comment by dw8547** [comment]
Moving on to channel in ods.csv/oda_2012.

dh = file from here: https://github.com/devinit/digital-platform/tree/master/country-year/oda.csv
ddw = table in ddw

source | no of unique channels
----------|-----------------------------
dh       | 10
ddw     | 22

**Comment by dw8547** [comment]
This is a space holder comment for @robtew to OK the channel.

**Comment by dw8547** [comment]
Moving on to individual donor sums.

dh = file from here: https://github.com/devinit/digital-platform/tree/master/country-year/oda.csv
ddw = table in ddw

id_from|sum|from_di_id|sum|% diff (dw compared to dh)
----------|------|---------------|-----|------------------------------------
||adaptation-fund|99043505|100
AE|8960170266|AE|8486247001|-6
afdb|1299655665|afdb|1266183300|-3
afdf|22459279968|afdf|27090699646|17
afesd|1068104584|||#DIV/0!
arab-fund-afesd|2562767803|arab-fund-afesd|5538376717|54
asdb-special-funds|8425866029|asdb-special-funds|8322933549|-1
AT|6518232390|AT|6459374658|-1
AU|30245316988|AU|30218168586|0
badea|348146453|badea|347051818|0
BE|12836684886|BE|12709944344|-1
CA|29014274652|CA|27158304670|-7
||ceb|244268402|100
CH|16576835871|CH|16371887360|-1
||cif|150690954|100
CZ|193394242|CZ|190159276|-2
DE|77227735564|DE|76653584940|-1
DK|14390859931|DK|14238081800|-1
ebrd|38237|||#DIV/0!
EE|10631822|EE|10190273|-4
ES|23933294792|ES|23537901430|-2
EU|105932161423|EU|109505111540|3
||fao|448615807|100
FI|5874410411|FI|5810538940|-1
FR|68264955612|FR|68035061084|0
gavi|6629071876|gavi|6400953467|-4
GB|68401714376|GB|67410064462|-1
gef|2856227751|gef|3443980938|17
||gggi|15641690|100
global-fund|20939659932|global-fund|20928770128|0
GR|1544024117|GR|1528066567|-1
ibrd|205612433|||#DIV/0!
ida|129459647043|ida|123158044909|-5
idb-specialfund|7782124509|idb-special-fund|8490957562|8
IE|4977787788|IE|4725154567|-5
ifad|0|ifad|0|#DIV/0!
imf|9808878969|||#DIV/0!
imf-concessional-trust-fund|7225286936|imf-concessional-trust-fund|17000143809|57
IS|68118099|IS|68360709|0
islamic-dev-bank|279618500|islamic-dev-bank|515263138|46
IT|11787252661|IT|11615041992|-1
JP|133917439045|JP|135877692673|1
KR|6812714162|KR|6598448379|-3
KW|2078769427|KW|2069376009|0
||KZ||#DIV/0!
LU|2246052068|LU|2190765940|-3
NL|36552042572|NL|36408323200|0
NO|29645449883|NO|28517786424|-4
nordic-dev-fund|320182288|nordic-dev-fund|319538614|0
NZ|2572136093|NZ|2560636783|0
ofid|1684459600|ofid|1676627038|0
osce|416112161|osce|571289542|27
PL|136646605|PL|140399320|3
PT|2801016879|PT|2789826116|0
SE|27645856013|SE|27296364301|-1
SI|19912915|SI|79516879|75
SK|15450895|SK|15429387|0
unaids|1885543296|unaids|1838266239|-3
undp|4449521040|undp|4238990873|-5
unece|75910616|unece|75962027|0
unfpa|2975741080|unfpa|2460932186|-21
unhcr|1271640166|unhcr|1270595141|0
unicef|8616737072|unicef|8630988661|0
unpbf|229976551|unpbf|319445015|28
unrwa|2364894452|unrwa|4184719470|43
US|209023774163|US|207879630351|-1
wfp|1935925547|wfp|1937418579|0
who|2167629176|who|2151078446|-1

**Comment by xriss** [comment]
> Could you please confirm if the name of the table in ddw must match the name of the .csv file as on https://github.com/devinit/digital-platform/tree/master/country-year or that the table column names must match the column headers in the .csv files, or both?

>Previously, the .csv files in https://github.com/devinit/digital-platform/tree/master/country-year contained columns labelled 'id', 'from_id', 'to_id'. These columns contain the identifiers for the DI entities. The DI instructions now are that anything that previously was an 'id' column, once automated, it becomes 'di_id', anything that previously was a 'from_id' column, once automated, it becomes 'from_di_id' and anything that previously was a 'to_id' column, once automated, it becomes 'to_di_id'.


@dw8547  They don't have to match, I can add more renaming logic beyond just switching the _ and - as long as I know what needs to be done. However the more names you have for the same things, the more complicated and confusing things will become and the greater the chance that mistakes will be made.

**Comment by dw8547** [comment]
This is a space holder comment for @robtew to OK the individual donor sums.

**Comment by dw8547** [comment]
Moving on to individual recipient sums.

dh = file from here: https://github.com/devinit/digital-platform/tree/master/country-year/oda.csv
ddw = table in ddw

id_to|sum|to_di_id|sum|% diff (dw compared to dh)
------|------|------------|-----|------------------------------------
AF|42803278714|AF|42323021987|-1
africa|13874312993|africa|13787680619|-1
AG|56918531|AG|56837472|0
AI|32348666|AI|32284252|0
AL|2877473423|AL|2884091487|0
AM|2810467164|AM|2780618245|-1
america|7824185620|america|8390839524|7
AO|2588471440|AO|2550572943|-1
AR|1109674235|AR|1107224488|0
asia|6614973209|asia|6457793401|-2
AZ|1983553258|AZ|1887183463|-5
BA|3859558119|BA|4038107671|4
BB|53724494|BB|53318342|-1
BD|19138593029|BD|18801022109|-2
BF|9650876240|BF|9631992838|0
BI|5452775098|BI|5726372441|5
|||bilateral-unspecified|195649326624|100
BJ|5909710567|BJ|6076853022|3
BO|7594770730|BO|7551623102|-1
BR|6968750565|BR|6279839549|-11
BT|976062668|BT|954363250|-2
BW|1760965895|BW|1767961229|0
BY|707562746|BY|702264992|-1
BZ|191924903|BZ|182117456|-5
CD|27459692519|CD|27184838945|-1
central-asia|1825630933|central-asia|1819917542|0
CF|2504369191|CF|2639355463|5
CG|3711106521|CG|3631353027|-2
CI|13101619049|CI|13095916523|0
CK|158019940|CK|157945918|0
CL|1027088234|CL|1097635979|6
CM|10583905193|CM|10555048255|0
CN|21445995927|CN|21506845553|0
CO|7718763452|CO|7356953235|-5
country-unspecified|197090531360|||'bilateral-unspecified in dw
CR|843775031|CR|815984389|-3
CU|757005914|CU|751824894|-1
CV|1890847374|CV|1887790864|0
DJ|1091004477|DJ|1088803912|0
DM|209389607|DM|208612090|0
DO|2009160121|DO|2014346870|0
DZ|2776814879|DZ|2760439813|-1
east-asia|1637959587|east-asia|1650209756|1
EC|2160656563|EC|2111604382|-2
EG|16848715717|EG|16958509146|1
ER|1069493473|ER|1054259791|-1
ET|30559840167|ET|30114742200|-1
europe|6101911476|europe|6238848256|2
ex-yugoslavia|234660114|ex-yugoslavia|237928170|1
FJ|658885981|FJ|655491731|-1
FM|1001389185|FM|966571253|-4
GA|823489312|GA|820849805|0
GD|148635050|GD|146404665|-2
GE|5208901113|GE|5134752278|-1
GH|17688735815|GH|17405332865|-2
GM|1105014913|GM|1305096829|15
GN|4096056530|GN|4287688683|4
GQ|283093200|GQ|279570037|-1
GT|3891171708|GT|3831870322|-2
GW|1385714306|GW|1358360148|-2
GY|1403568672|GY|1379853400|-2
HN|6037781128|HN|5988884325|-1
HR|1010328799|HR|1018542221|1
HT|12227444898|HT|12007692872|-2
ID|25354275459|ID|25254706696|0
IN|34032449808|IN|33161845063|-3
IQ|38329209151|IQ|40243397483|5
IR|963487216|IR|956569198|-1
JM|1069216163|JM|1064995168|0
JO|8201529977|JO|8481537869|3
KE|17653408861|KE|17603141438|0
KG|2563127984|KG|2517075566|-2
KH|6043171491|KH|5961120532|-1
KI|358693334|KI|356402393|-1
KM|600435823|KM|592967630|-1
KN|125123119|KN|124662814|0
KP|783715257|KP|779460230|-1
KZ|1597410120|KZ|1576264416|-1
LA|3307181520|LA|3244038865|-2
LB|5315804860|LB|5639932132|6
LC|239537379|LC|238423980|0
LK|8496784353|LK|8262115808|-3
LR|7164478256|LR|7128165832|-1
LS|1716196085|LS|1679629877|-2
LY|1042124790|LY|1062686219|2
MA|12714335989|MA|12975555219|2
MD|2771582099|MD|2742922225|-1
ME|732132086|ME|784742920|7
MG|7831432686|MG|7987958660|2
MH|600095647|MH|544036700|-10
middle-east|2830278494|middle-east|2871583907|1
MK|1639203481|MK|1697621846|3
ML|10810462292|ML|10987538065|2
MM|11427450016|MM|11340481520|-1
MN|2771135417|MN|2728309798|-2
MR|3673559343|MR|4013831508|8
MS|313670158|MS|313464191|0
MU|1204540930|MU|1205589028|0
MV|426899953|MV|433274247|1
MW|11160771790|MW|11163178397|0
MX|4142375124|MX|4178821144|1
MY|2510442987|MY|2514827994|0
MZ|18102703074|MZ|18045810845|0
NA|2079247869|NA|2069993946|0
NE|6715545531|NE|6741169528|0
NG|28005345488|NG|27557528006|-2
NI|6569569312|NI|6484067030|-1
north-central-america|2814233203|north-central-america|2744029711|-3
north-of-sahara|2084177731|north-of-sahara|2156928329|3
NP|6718498055|NP|6556409646|-2
NR|268250281|NR|269227578|0
NU|138593251|NU|138683804|0
oceania|2117887451|oceania|2112757680|0
OM|221112847|OM|311720571|29
PA|634034222|PA|633349873|0
PE|5662170038|PE|5539726464|-2
PG|4784111053|PG|4777314500|0
PH|9971414866|PH|9914331196|-1
PK|23158639726|PK|22448910434|-3
PS|16576680916|PS|17307404305|4
PW|262542653|PW|259220189|-1
PY|1439585980|PY|1434901789|0
RS|7534040723|RS|8272452092|9
RW|8866414404|RW|8852234750|0
SA|28577175|SA|28432220|-1
SB|2586119034|SB|2596735891|0
SC|209132410|SC|214998416|3
SD|14365903395|SD|15653978910|8
SH|621149918|SH|621076377|0
SL|4380546744|SL|4606497718|5
SN|10661268370|SN|10723246186|1
SO|5507081484|SO|5463443360|-1
south-america|1875853152|south-america|1819916649|-3
south-asia|922909299|south-asia|930157545|1
south-central-asia|1528860205|south-central-asia|1641856930|7
south-of-sahara|18049222450|south-of-sahara|18040411672|0
SR|737002855|SR|734989401|0
SS|4109925355|SS|2954633428|-39
ST|464822052|ST|592710879|22
SV|2364071940|SV|2331034098|-1
SY|4250773403|SY|4518311160|6
SZ|689538975|SZ|688227052|0
TC|12899114|TC|12880478|0
TD|3788437954|TD|3783180020|0
TG|3471580203|TG|3413303941|-2
TH|4176416610|TH|4210791408|1
TJ|2629245968|TJ|2593679641|-1
TK|150796309|TK|150471333|0
TL|2279895212|TL|2259548873|-1
TM|198403771|TM|200760306|1
TN|6686496134|TN|7073596059|5
TO|494585500|TO|492485634|0
TR|15370036196|TR|17116534599|10
TT|68622903|TT|68208372|-1
TV|175502285|TV|175627600|0
TZ|27392324537|TZ|27318706231|0
UA|4889116528|UA|4914754086|1
UG|17644697966|UG|17577008877|0
UY|363708027|UY|361651418|-1
UZ|1809840064|UZ|1762208306|-3
VC|183978413|VC|182556993|-1
VE|422894640|VE|419540687|-1
VN|29413618916|VN|28648820036|-3
VU|799870446|VU|800002511|0
west-indies|939625139|west-indies|873847258|-8
WF|828107472|WF|824363731|0
WS|784672072|WS|781041658|0
XK|3026569380|XK|2856539299|-6
YE|5079065701|YE|5212837375|3
YT|2001210854|YT|1984904481|-1
ZA|9133224775|ZA|9326234364|2
ZM|13019570325|ZM|13044389762|0
ZW|5509976806|ZW|5450742145|-1

@robtew are these differences in the total $ ODA for the different recipients acceptable?

**Comment by dw8547** [comment]
Moving on to individual recipient sums.

dh = file from here: https://github.com/devinit/digital-platform/tree/master/country-year/oda.csv
ddw = table in ddw

id_to|sum|to_di_id|sum|% diff (dw compared to dh)
------|------|------------|-----|------------------------------------
AF|42803278714|AF|42323021987|-1
africa|13874312993|africa|13787680619|-1
AG|56918531|AG|56837472|0
AI|32348666|AI|32284252|0
AL|2877473423|AL|2884091487|0
AM|2810467164|AM|2780618245|-1
america|7824185620|america|8390839524|7
AO|2588471440|AO|2550572943|-1
AR|1109674235|AR|1107224488|0
asia|6614973209|asia|6457793401|-2
AZ|1983553258|AZ|1887183463|-5
BA|3859558119|BA|4038107671|4
BB|53724494|BB|53318342|-1
BD|19138593029|BD|18801022109|-2
BF|9650876240|BF|9631992838|0
BI|5452775098|BI|5726372441|5
|||bilateral-unspecified|195649326624|100
BJ|5909710567|BJ|6076853022|3
BO|7594770730|BO|7551623102|-1
BR|6968750565|BR|6279839549|-11
BT|976062668|BT|954363250|-2
BW|1760965895|BW|1767961229|0
BY|707562746|BY|702264992|-1
BZ|191924903|BZ|182117456|-5
CD|27459692519|CD|27184838945|-1
central-asia|1825630933|central-asia|1819917542|0
CF|2504369191|CF|2639355463|5
CG|3711106521|CG|3631353027|-2
CI|13101619049|CI|13095916523|0
CK|158019940|CK|157945918|0
CL|1027088234|CL|1097635979|6
CM|10583905193|CM|10555048255|0
CN|21445995927|CN|21506845553|0
CO|7718763452|CO|7356953235|-5
country-unspecified|197090531360|||'bilateral-unspecified in dw
CR|843775031|CR|815984389|-3
CU|757005914|CU|751824894|-1
CV|1890847374|CV|1887790864|0
DJ|1091004477|DJ|1088803912|0
DM|209389607|DM|208612090|0
DO|2009160121|DO|2014346870|0
DZ|2776814879|DZ|2760439813|-1
east-asia|1637959587|east-asia|1650209756|1
EC|2160656563|EC|2111604382|-2
EG|16848715717|EG|16958509146|1
ER|1069493473|ER|1054259791|-1
ET|30559840167|ET|30114742200|-1
europe|6101911476|europe|6238848256|2
ex-yugoslavia|234660114|ex-yugoslavia|237928170|1
FJ|658885981|FJ|655491731|-1
FM|1001389185|FM|966571253|-4
GA|823489312|GA|820849805|0
GD|148635050|GD|146404665|-2
GE|5208901113|GE|5134752278|-1
GH|17688735815|GH|17405332865|-2
GM|1105014913|GM|1305096829|15
GN|4096056530|GN|4287688683|4
GQ|283093200|GQ|279570037|-1
GT|3891171708|GT|3831870322|-2
GW|1385714306|GW|1358360148|-2
GY|1403568672|GY|1379853400|-2
HN|6037781128|HN|5988884325|-1
HR|1010328799|HR|1018542221|1
HT|12227444898|HT|12007692872|-2
ID|25354275459|ID|25254706696|0
IN|34032449808|IN|33161845063|-3
IQ|38329209151|IQ|40243397483|5
IR|963487216|IR|956569198|-1
JM|1069216163|JM|1064995168|0
JO|8201529977|JO|8481537869|3
KE|17653408861|KE|17603141438|0
KG|2563127984|KG|2517075566|-2
KH|6043171491|KH|5961120532|-1
KI|358693334|KI|356402393|-1
KM|600435823|KM|592967630|-1
KN|125123119|KN|124662814|0
KP|783715257|KP|779460230|-1
KZ|1597410120|KZ|1576264416|-1
LA|3307181520|LA|3244038865|-2
LB|5315804860|LB|5639932132|6
LC|239537379|LC|238423980|0
LK|8496784353|LK|8262115808|-3
LR|7164478256|LR|7128165832|-1
LS|1716196085|LS|1679629877|-2
LY|1042124790|LY|1062686219|2
MA|12714335989|MA|12975555219|2
MD|2771582099|MD|2742922225|-1
ME|732132086|ME|784742920|7
MG|7831432686|MG|7987958660|2
MH|600095647|MH|544036700|-10
middle-east|2830278494|middle-east|2871583907|1
MK|1639203481|MK|1697621846|3
ML|10810462292|ML|10987538065|2
MM|11427450016|MM|11340481520|-1
MN|2771135417|MN|2728309798|-2
MR|3673559343|MR|4013831508|8
MS|313670158|MS|313464191|0
MU|1204540930|MU|1205589028|0
MV|426899953|MV|433274247|1
MW|11160771790|MW|11163178397|0
MX|4142375124|MX|4178821144|1
MY|2510442987|MY|2514827994|0
MZ|18102703074|MZ|18045810845|0
NA|2079247869|NA|2069993946|0
NE|6715545531|NE|6741169528|0
NG|28005345488|NG|27557528006|-2
NI|6569569312|NI|6484067030|-1
north-central-america|2814233203|north-central-america|2744029711|-3
north-of-sahara|2084177731|north-of-sahara|2156928329|3
NP|6718498055|NP|6556409646|-2
NR|268250281|NR|269227578|0
NU|138593251|NU|138683804|0
oceania|2117887451|oceania|2112757680|0
OM|221112847|OM|311720571|29
PA|634034222|PA|633349873|0
PE|5662170038|PE|5539726464|-2
PG|4784111053|PG|4777314500|0
PH|9971414866|PH|9914331196|-1
PK|23158639726|PK|22448910434|-3
PS|16576680916|PS|17307404305|4
PW|262542653|PW|259220189|-1
PY|1439585980|PY|1434901789|0
RS|7534040723|RS|8272452092|9
RW|8866414404|RW|8852234750|0
SA|28577175|SA|28432220|-1
SB|2586119034|SB|2596735891|0
SC|209132410|SC|214998416|3
SD|14365903395|SD|15653978910|8
SH|621149918|SH|621076377|0
SL|4380546744|SL|4606497718|5
SN|10661268370|SN|10723246186|1
SO|5507081484|SO|5463443360|-1
south-america|1875853152|south-america|1819916649|-3
south-asia|922909299|south-asia|930157545|1
south-central-asia|1528860205|south-central-asia|1641856930|7
south-of-sahara|18049222450|south-of-sahara|18040411672|0
SR|737002855|SR|734989401|0
SS|4109925355|SS|2954633428|-39
ST|464822052|ST|592710879|22
SV|2364071940|SV|2331034098|-1
SY|4250773403|SY|4518311160|6
SZ|689538975|SZ|688227052|0
TC|12899114|TC|12880478|0
TD|3788437954|TD|3783180020|0
TG|3471580203|TG|3413303941|-2
TH|4176416610|TH|4210791408|1
TJ|2629245968|TJ|2593679641|-1
TK|150796309|TK|150471333|0
TL|2279895212|TL|2259548873|-1
TM|198403771|TM|200760306|1
TN|6686496134|TN|7073596059|5
TO|494585500|TO|492485634|0
TR|15370036196|TR|17116534599|10
TT|68622903|TT|68208372|-1
TV|175502285|TV|175627600|0
TZ|27392324537|TZ|27318706231|0
UA|4889116528|UA|4914754086|1
UG|17644697966|UG|17577008877|0
UY|363708027|UY|361651418|-1
UZ|1809840064|UZ|1762208306|-3
VC|183978413|VC|182556993|-1
VE|422894640|VE|419540687|-1
VN|29413618916|VN|28648820036|-3
VU|799870446|VU|800002511|0
west-indies|939625139|west-indies|873847258|-8
WF|828107472|WF|824363731|0
WS|784672072|WS|781041658|0
XK|3026569380|XK|2856539299|-6
YE|5079065701|YE|5212837375|3
YT|2001210854|YT|1984904481|-1
ZA|9133224775|ZA|9326234364|2
ZM|13019570325|ZM|13044389762|0
ZW|5509976806|ZW|5450742145|-1

@robtew are these differences in the total $ ODA for the different recipients acceptable?

**Comment by dw8547** [comment]
Hi @xriss & @notshi, I've put together the checks requested by @robtew & we are just waiting for @robtew to OK the differences between the contents in https://github.com/devinit/digital-platform/tree/master/country-year/oda.csv and in fact.oda_2012. This is the most important & biggest of the automated data series, so hopefully once this one is out of the way things will move a bit quicker.

**Comment by dw8547** [comment]
Hi @xriss & @notshi, I've put together the checks requested by @robtew & we are just waiting for @robtew to OK the differences between the contents in https://github.com/devinit/digital-platform/tree/master/country-year/oda.csv and in fact.oda_2012. This is the most important & biggest of the automated data series, so hopefully once this one is out of the way things will move a bit quicker.

**Comment by notshi** [comment]
Thanks, @dw8547. If possible, try not editing our comments to reply to it, quoting is fine, thanks.

**Comment by dw8547** [comment]
@notshi, NP. My apologies. I've edited almost all of them up to now. Won't from now on.

**Comment by dw8547** [comment]
Dead issue.
