### ISSUE TITLE
Missing tables

### ISSUE THREAD

**Issue by epicallan** [devinit/digital-platform#254]
Tables that couldn't be found, currently commented out in datamap.raw.js since they stop the script from running.

```
/country-year/remittances-pp.csv <- data_series."rems_pp" 
```

**Comment by dw8547** [comment]
Thanks for spotting @epicallan! Updated [datamap_raw.js](https://github.com/devinit/digital-platform/blob/development/nodejs/js/datamap_raw.js), please try again!

Let's keep this issue open until we are sure I've not missed anything. List of name changes coming soon (`rems_pp.csv` → `remittances-pp.csv` is one of them).

**Comment by epicallan** [comment]
That was all. 😃

**Comment by epicallan** [comment]
@dw8547 I have also updated the dev branch

**Comment by dw8547** [comment]
@epicallan, am I working on master??? OMG. (FACEPALM).
