### ISSUE TITLE
Confirm remaining unsued concepts

### ISSUE THREAD

**Issue by dw8547** [devinit/digital-platform#256]
Hi @epicallan, I need your help with this one. I can't figure out for sure (using the DH web app source code) if these are used or not:

1) **dfis-out**: string found in [components/AreaTree/areaTreeDirective.js](https://github.com/devinit/datahub-angular/public/diConcept/components/AreaTree/areaTreeDirective.js) & [pages/Country/country_print.html](https://github.com/devinit/datahub-angular/public/diConcept/pages/Country/country_print.html)
2) **dfis-out-dev**: string found in [components/AreaTree/areaTreeDirective.js](https://github.com/devinit/datahub-angular/public/diConcept/components/AreaTree/areaTreeDirective.js)
3) **ethiopia-nigeria-r3**: string found in [charts/angular/chartjs.js](https://github.com/devinit/datahub-angular/public/diConcept/charts/angular/chartjs.js)
4) **ethiopia-nigeria-r7**: string found in [charts/angular/chartjs.js](https://github.com/devinit/datahub-angular/public/diConcept/charts/angular/chartjs.js) & [pages/debug/debug.html](https://github.com/devinit/datahub-angular/public/diConcept/pages/debug/debug.html)
5) **fdi-out**: string found in [components/AreaTree/areaTreeDirective.js](https://github.com/devinit/datahub-angular/public/diConcept/components/AreaTree/areaTreeDirective.js), [components/TreeChart/treeChartInternationalDirective.js](https://github.com/devinit/datahub-angular/public/diConcept/components/TreeChart/treeChartInternationalDirective.js), [pages/Country/country_print.html](https://github.com/devinit/datahub-angular/public/diConcept/pages/Country/country_print.html), [charts/angular/chartjs.js](https://github.com/devinit/datahub-angular/public/diConcept/charts/angular/chartjs.js)
6) **in-oof-net**: string not found anywhere in the DH web app source code
7) **long-debt-disbursement-in**: string found in [components/AreaTree/areaTreeDirective.js](https://github.com/devinit/datahub-angular/public/diConcept/components/AreaTree/areaTreeDirective.js)
8) **long-debt-net-official-in**: string found in [components/AreaTree/areaTreeDirective.js](https://github.com/devinit/datahub-angular/public/diConcept/components/AreaTree/areaTreeDirective.js)
9) **oda-capital-repayments**: string found in [components/AreaTree/areaTreeDirective.js](https://github.com/devinit/datahub-angular/public/diConcept/components/AreaTree/areaTreeDirective.js)
10) **oda-interest-payments**: string found in [components/AreaTree/areaTreeDirective.js](https://github.com/devinit/datahub-angular/public/diConcept/components/AreaTree/areaTreeDirective.js
11) **remittances**: string found in several locations
12) **ssc-out**: string found in [components/AreaTree/areaTreeDirective.js](https://github.com/devinit/datahub-angular/public/diConcept/components/AreaTree/areaTreeDirective.js)

Please **confirm if OK to remove** from [concepts.csv](https://github.com/devinit/digital-platform/blob/development/concepts.csv).

**Comment by dw8547** [comment]
Hi @malmike, @epicallan said you could help out with this tomorrow morning.

**Comment by dw8547** [comment]
Good morning @malmike, I'm ready when you are.

**Comment by malmike** [comment]
Afternoon @dw8547, Sorry went directly into checking whether the items above were being used

**Comment by dw8547** [comment]
Thanks @malmike! Please keep me posted :)

**Comment by malmike** [comment]
I have been told that most of them are used in data retrieval by the data service file. And on cross checking whether they were being utilized, I got the following result:-
1 - Not used; Ran the country print page and the country profile page;
2 - Not used; Ran the country print page and the country profile page;
3 - Not used; Ran the country print page for ethopia, nigeria and united kingdom;
4 - Not used; Ran the country print page for ethopia, nigeria and united kingdom;
5 - Not used; Ran the country print page and the country profile page;
6 - Not fount in the DH web application source code;
7 - Not used; Ran the country profile page and the country print page;
8 - Not used; Ran the country print page and the country profile page;
9 - Not used; Ran the country print page and the country profile page;
10 - Not used; Ran the country print page and the country profile page;
11 - Appears to be used;
12 - Not used; Ran the country print page and the country profile page;

**Comment by malmike** [comment]
The reason I was mainly running the country profile or country print page is because the directives or components that were mentioned above would require either one or both of those pages to be loading in order to run

**Comment by dw8547** [comment]
Thank you @malmike. Will remove 1 - 10 & 12. Out of curiosity, which chart is 11 used with?

**Comment by malmike** [comment]
Remittances is not applied as it is, what I found was remittances-individual-devcountries and that is found in country print of donor countries. Am not sure if that is in relation to the initial query, 'remittances: string found in several locations'.

**Comment by dw8547** [comment]
Thanks @malmike. What I'm after really is if the web app data model at any point takes from [remittances.csv](https://github.com/devinit/digital-platform/blob/development/country-year/remittances.csv) (or any of the other files that use the names from the list above + .csv). If not, I want to delete the file(s) as it's clutter & @epicallan says this slows down the web app. If you haven't found a reference to 'remittances' on it's own, I presume it's OK to delete. Many thanks.

**Comment by dw8547** [comment]
https://github.com/devinit/digital-platform/commit/d7f7b63ec1d05cbf5522990fb22454cdc610754f.
