### ISSUE TITLE
Reference file: country.csv -> entity.csv

### ISSUE THREAD

**Issue by lapidus** [devinit/digital-platform#39]
Rename country.csv to entities.csv?

use?

id | type | name
------------ | ------------- | -------------
SE | country | Sweden

instead of:
country	country-name

**Comment by bill-anderson** [comment]
Others are singular. entity.csv ?? OK?

**Comment by lapidus** [comment]
Yes!

**Comment by bill-anderson** [comment]
Done
Columns in file are now id, type, name, region, iso-alpha-2, iso-alpha-3, income-group

**Comment by lapidus** [comment]
After quick check:
1. Type needs to be populated for all.
2. Sub-concepts should have their own rows.
