### ISSUE TITLE
Resources reference file

### ISSUE THREAD

**Issue by lapidus** [devinit/digital-platform#4]
Great if someone could add a reference file for resource flows so I can start modeling these on the website.

| Code | Name |
| --- | --- |
| fdi | Foreign Direct Investment |
| oda | Official Development Assistance |

**Comment by timstrawson** [comment]
@lapidus @bill-anderson  is this still outstanding? (I see the comment is from may last year). if so I'll compile a reference file today

**Comment by bill-anderson** [comment]
It's assigned to @lapidus to check whether it is needed - I suspect that it may not be

**Comment by dw8547** [comment]
Dead issue.

**Comment by dw8547** [comment]
Dead issue.
