### ISSUE TITLE
Suggested country-year file formats

### ISSUE THREAD

**Issue by lapidus** [devinit/digital-platform#40]
"Simple" - use:
id, year, value
https://github.com/devinit/digital-platform/blob/master/country-year/infant-mortality.csv

"Composite" - use:
id, dim, dim, year, value
https://github.com/devinit/digital-platform/blob/master/country-year/employment-by-sector.csv

"Multi" - use:
id-from, id-to, dim, dim, dim, year, value
https://raw.githubusercontent.com/devinit/digital-platform/master/country-year/oda.csv

**Comment by bill-anderson** [comment]
I thought what you were suggesting on Friday was to represent all ids as dims. That seemed to make sense to me. The "ids" are all just country/entities, right?

**Comment by lapidus** [comment]
Indeed, they are just dims of the type id/entitiy
