### ISSUE TITLE
API queries & responses

### ISSUE THREAD

**Issue by lapidus** [devinit/digital-platform#41]
Here I am documenting some useful API responses so that we can identify potential bottlenecks "upstream".

**Get reference lists**
api/entities/

```
[
   { id : "SE", type: "country", name : "Sweden"},
   { ... }
]
```

api/regions/

```
[
   { id : "s_asia", name : "South Asia"},
   { ... }
]
```

**Get stats**
api/indicators/?query={ "id" : "lex"}

```
{
    meta : {
        concept : "lex",
        name : "Life Expectancy",
        source : "World Bank"
        something_else : "Lorem ipsum"
    }
    data : 
       [
           { id : "SE", year : 2014, value : 81},
           { ... }
       ]

}

```

api/indicators/?query={ "id" : "oda" }

```
[
   { "id-from" : "SE", "id-to": "AF", year: 2014, channel : "H", type: "C", bundle: "E", sector : "A" },
   { ... }
]
```

api/indicators/?query={ "id" : "income_share"}

```
[
   { "id" : "SE", year: 2014, q1 : 25, q2 : 20, q3: 30, q4: 10 },
   { ... }
]
```

**Advanced queries**
api/indicators/?query={ groupBy : { keys : ["id-from", "sector"], conds : {"id" : "oda", "year" : 2012} }

```
[
   { "id-from" : "SE", year: 2012, sector : "A", value : 100 },
   { "id-from" : "SE", year: 2012, sector : "B", value : 110 },
   { "id-from" : "US", year: 2012, sector : "A", value : 1000 }, 
   { ... }
]
```

**Comment by akmiller01** [comment]
Alright, I've put together a mock API that mimics most of the functionality described here. I'll put a live version up on a staging server so you can try it yourself in a moment. Some issues I've noticed:

1. Entities refer to themselves by "id" while regions refer to themselves as "region." This should be changed to "id" in the region.csv
2. In the indicators API, it's difficult to distinguish between the "id" of the indicator, and the "id" of the data within the indicator. Right now, the mock API uses the "id" field to select the indicator, and then the remaining fields within the data of that indicator to filter the data. E.g. 
```
/api/indicators/?query={"id":"life-expectancy-at-birth","year":2000}
```
 allows you to pick the life-expectancy-at-birth indicator where year==2000. Here's one sample row: 
```
{"id":"AW","year":2000,"value":73.72060976},
```
But it will not allow you to pick life-expectancy-at-birth where "id"=="AW." I haven't hooked it into concepts.csv, so perhaps that will make things more straightforward.

**Comment by akmiller01** [comment]
Well, it's online, but I didn't realize raw github would give me so much trouble with cross-domain security. Unfortunately, to test this out, you either need to open Chrome like:
```
"C:\Program Files (x86)\Google\Chrome\Application\chrome.exe" --user-data-dir="C:/Chrome dev session2" --disable-web-security
```
for window or like:
```
open -a Google\ Chrome --args --disable-web-securityalexmillersmbp:~ Alex$ open -a Google\ Chrome --args --disable-web-security
```
for OSX.

The three URLs are:
1. Regions: http://akmiller01.people.wm.edu/api/regions/
2. Entities: http://akmiller01.people.wm.edu/api/entities/
3. Indicators: http://akmiller01.people.wm.edu/api/indicators/

Both regions and entities will return content without a query parameter, but indicators needs a query.
Some examples:
http://akmiller01.people.wm.edu/api/indicators/?query={"id":"life-expectancy-at-birth","year":2000}
http://akmiller01.people.wm.edu/api/regions/?query={"DAC%20Continent%20Code":798}
http://akmiller01.people.wm.edu/api/entities/?query={"income-group":"LDCs"}

On that note: we may want to remove spaces from variable names like "DAC Continent Code."

**Comment by lapidus** [comment]
@akmiller01 "In the indicators API, it's difficult to distinguish between the "id" of the indicator, and the "id" of the data within the indicator." Yes, maybe better to stick to "concept" for the id of concepts?

**Comment by akmiller01** [comment]
Alright @lapidus and @bill-anderson . Fixed the security issue (You no longer need to start Chrome in a development mode), and edited the mock API to reflect those changes.

Region and Entity APIs behave as before, but now the indicator API takes on the following behavior.

If your search query on indicators does not contain the key "concept," it will return meta-data filtered by the parameters in query. Like so:

http://akmiller01.people.wm.edu/api/indicators/?query={"source":"WDI"}

Will return this sample row among many:
```
{"series":"country-year","id":"youth-unemployment","type":"simple","parent":0,"name":"youth unemployment %","columns":"id, year, value","description":"youth unemployment %","default-scale":"lin","":0,"uom":"percent","source":"WDI","calculation":0,"format":0}
```
Or if you want meta-data on an indicator by ID:

http://akmiller01.people.wm.edu/api/indicators/?query={"id":"youth-unemployment"}

But if you want the data itself inside the concept, you need to refer to it as a "concept" in the query. Like so:

http://akmiller01.people.wm.edu/api/indicators/?query={"concept":"youth-unemployment"}

At which point the remaining parameters in "query" are applied to filtering the data itself:

http://akmiller01.people.wm.edu/api/indicators/?query={"concept":"youth-unemployment","year":2010,"id":"ZW"}

If you want the source, I've uploaded it here:
https://github.com/akmiller01/alexm-util/tree/master/DevInit/api

**Comment by akmiller01** [comment]
Advanced Query:
http://akmiller01.people.wm.edu/api/indicators/?query={"concept":"oda","group":{"sum":"value\r","by":["id-from","id-to"]}}

**Comment by dw8547** [comment]
Dead issue/FYI.
