### ISSUE TITLE
Populate all entities with region code

### ISSUE THREAD

**Issue by bill-anderson** [devinit/digital-platform#45]
entity.csv requires a region (from region.csv) for each id (excluding type=organisation) 
@akmiller01 could you patch in the missing ones

**Comment by akmiller01** [comment]
I'll start on it now.

**Comment by akmiller01** [comment]
What about type=region? Some fit, but "Africa, regional" doesn't fit into north or south Africa.

**Comment by bill-anderson** [comment]
The joys of OECD DAC classifications. @robtew this is one for you to make a random call on

**Comment by bill-anderson** [comment]
@akmiller01 the answer is that there is no answer. So leave it blank. Ditto for Asia, regional

from Rob ...

That's a tricky one to answer.  We have the same problem with "Americas, regional" and "Asia, regional".  When we are analysing ODA to SSA vs ODA to N. Africa (or doing something similar for Asia or the Americas) we usually impute a proportion of the aid to 'Africa, regional' to each of the sub regions.  For example, if ODA to 'Africa, regional' was $10m and total ODA to SSA and N. Africa stood at $900m and $100m respectively, we would allocate $9m of the 'Africa, regional' pot to SSA and $1m to N. Africa (As SSA gets 90% of the remaining ODA to Africa and N. Africa gets 10%).  ODA to 'Asia, regional' has to be divided up 3 ways as there are 3 sub-regions.  The alternative would be to leave the continent-wide regional ODA out of the totals for the sub-regions altogether.  I'm not sure if that makes sense - let me know if you want to discuss this further.

**Comment by akmiller01** [comment]
Roger.

**Comment by akmiller01** [comment]
One quick observation: Before I started, Afghanistan was pre-filled in as "South & Central Asia." Is this not considered the "Middle East?" I think it gets a bit confusing because the category is called "Middle East Asia" even though it's referring to the far West of Asia.
