### ISSUE TITLE
Migrate remaining csv files from /di-only/country-year to /country-year

### ISSUE THREAD

**Issue by akmiller01** [devinit/digital-platform#46]
Hey @bill-anderson,

I just finished migrating and formatting every csv described in concepts.csv from /di-only/country-year to /country-year. Below is a table describing the remaining csvs within /di-only/country-year. Would you like me to format, migrate, and add these to concepts.csv?

| concept | type | columns | needsFormatting |
|-----------------------------------|-----------|---------------------------------------------------------------|-----------------|
| bundle_fdi | composite | country, year, category, bundle_fdi | TRUE |
| in-oda-gross-bundle | composite | country, bundle, year, in-oda-gross-bundle | TRUE |
| in-oda-gross-channel | composite | country, channel, year, in-oda-gross-channel | TRUE |
| in-oda-gross-channel-bundle | composite | country, channel, bundle, year, in-oda-gross-channel-bundle | TRUE |
| in-oda-gross-sector | composite | country, sector, year, in-oda-gross-sector | TRUE |
| in-oda-gross-sector-bundle | composite | country, sector, bundle, year, in-oda-gross-sector-bundle | TRUE |
| in-oda-gross-sector-channel | composite | country, sector, channel, year, in-oda-gross-sector-channel | TRUE |
| in-oof-bundle | composite | country, year, oof-bundle, in-oof-bundle | TRUE |
| oda-gross-bl-dest-region | composite | country, region, year, oda-gross-bl-dest-region | TRUE |
| oda-sector-aid-bundle-usd-current | composite | country, year, sector, aid-bundle, value | TRUE |
| oda-sector-usd-current | composite | country, year, sector, value | TRUE |
| out-oda-gross-bundle | composite | country, bundle, year, out-oda-gross-bundle | TRUE |
| out-oda-gross-channel | composite | country, channel, year, out-oda-gross-channel | TRUE |
| out-oda-gross-channel-bundle | composite | country, channel, bundle, year, out-oda-gross-channel-bundle | TRUE |
| out-oda-gross-sector | composite | country, sector, year, out-oda-gross-sector | TRUE |
| out-oda-gross-sector-bundle | composite | country, sector, bundle, year, out-oda-gross-sector-bundle | TRUE |
| out-oda-gross-sector-channel | composite | country, sector, channel, year, out-oda-gross-sector-channel | TRUE |
| out-oof-bundle | composite | country, year, oof-bundle, out-oof-bundle | TRUE |
| bl_ha | multi | country_from, country_to, year, bl_ha | TRUE |
| bl_remittances | multi | country_from, country_to, year, bl_remittances | TRUE |
| oda-gross-bl | multi | country-from, country-to, year, oda-gross-bl | TRUE |
| oda-gross-bl-bundle | multi | country-from, country-to, bundle, year, oda-gross-bl-bundle | TRUE |
| oda-gross-bl-channel | multi | country-from, country-to, channel, year, oda-gross-bl-channel | TRUE |
| oda-gross-bl-sector | multi | country-from, country-to, sector, year, oda-gross-bl-sector | TRUE |
| oof | multi | year, country-from, country-to, sector, bundle, channel, oof | TRUE |
| from_fdi_profits | simple | country, year, from_fdi_profits | TRUE |
| from_illicitfinance | simple | country, year, from_illicitfinance | TRUE |
| from_trademispricing | simple | country, year, from_trademispricing | TRUE |
| from-oda-capital | simple | country, year, from-oda-capital | TRUE |
| from-oda-interest | simple | country, year, from-oda-interest | TRUE |
| from-oof-capital | simple | country, year, from-oof-capital | TRUE |
| from-oof-interest | simple | country, year, from-oof-interest | TRUE |
| in_fdi | simple | country, year, in_fdi | TRUE |
| in_fdi_profits | simple | country, year, in_fdi_profits | TRUE |
| in_ha | simple | country, year, in_ha | TRUE |
| in_longdebt | simple | country, year, in_longdebt | TRUE |
| in_oofs_gross | simple | country, year, in_oofs_gross | TRUE |
| in_portfeq | simple | country, year, in_portfeq | TRUE |
| in_remittances | simple | country, year, in_remittances | TRUE |
| in_shortdebt | simple | country, year, in_shortdebt | TRUE |
| in-oda-gross | simple | country, year, in-oda-gross | TRUE |
| in-oof-gross | simple | country, year, in-oof-gross | TRUE |
| oda-per-poor-person | simple | country, year, value | TRUE |
| out_DFIs_coms | simple | country, year, out_DFIs_coms | TRUE |
| out_DFIs_disbs | simple | country, year, out_DFIs_disbs | TRUE |
| out_fdi | simple | country, year, out_fdi | TRUE |
| out_PDA | simple | country, year, out_PDA | TRUE |
| out_remittances | simple | country, year, out_remittances | TRUE |
| out-oda-gross | simple | country, year, out-oda-gross | TRUE |
| out-oof-gross | simple | country, year, out-oof-gross | TRUE |
| to-oda-capital | simple | country, year, to-oda-capital | TRUE |
| to-oda-interest | simple | country, year, to-oda-interest | TRUE |
| to-oof-capital | simple | country, year, to-oof-capital | TRUE |
| to-oof-interest | simple | country, year, to-oof-interest | TRUE |

**Comment by bill-anderson** [comment]
Let's hold off doing anything on this until @timstrawson and @robtew agree which composites are required

**Comment by akmiller01** [comment]
@bill-anderson, let me know when we decide to move these and if they need any recoding. I wrote a quick batch script that takes an input folder and an output folder, recognizes our "simple" type definition, renames headers, replaces underscores with dashes, and moves them to the output folder: https://github.com/akmiller01/alexm-util/blob/master/DevInit/move_csv.py

The code can also easily be modified to recode composite measures to certain specifications.

**Comment by bill-anderson** [comment]
Great. Waiting to hear from Tim (and Dan) on what the needs are. It is worth you mentioning your batch jobbie to Tim now as he might already be doing grunt work on this
