### ISSUE TITLE
names not matching

### ISSUE THREAD

**Issue by erikbergsten** [devinit/digital-platform#47]
Some of the country-year files dont have names exactly matching the lines in concepts.csv, i've noticed the following ones:

govtspend-pc /= govtspend_pc
govtspend-USD /= govtspend_USD
intlresources-total /= intlresources_total

population-urban-rural /= population-rural-urban

taxrev-%GDP /= taxrev_%GDP

**Comment by bill-anderson** [comment]
@akmiller01 could you double-check that 
*  all underscores are replaced with hyphens
*  other name discrepancies (eg population-urban-rural)

**Comment by akmiller01** [comment]
Done.
