### ISSUE TITLE
Do we need to hardcode recipient / donor / crossover or do we infer it for each visualization?

### ISSUE THREAD

**Issue by lapidus** [devinit/digital-platform#48]
Previously in `entity.csv` we had a column for representing donor/recipient/crossover status. 

I am not sure this is needed going forward but would like to double-check the scenarios with you:

**ODA treemap:**
In the ODA treemap we want to display a level for "FROM" and one for "TO". By making a query to the database before we populate the chart/dropdowns we can infer the categorization from the data. This would likely make it easier to maintain?

http://di-api.herokuapp.com/group/inds/?query={%22keys%22%20:%20[%22country-to%22],%20%22conds%22%20:%20{%22concept%22%20:%20%22oda%22,%20%22year%22%20:%202012}} 
(This query is currently slow but will be faster soon with caching.)

**Country profiles:**
Here we are using something like "Developing countries only": 
http://invis.io/4F27L8I7S

And "Donor countries only":
https://projects.invisionapp.com/share/4F27L8I7S#/screens/56298156

How do we tackle this? Inferring or keeping a list?

**Resource flows:**
Good if you can specify an approach for this visualization as well. Any of the suggested above or other?

**Comment by akmiller01** [comment]
Assuming we can receive this sort of data already formatted from an API, it may be smart to re-arrange this sort of financial data into a single row like:

| id | year | commercial-inflow | commercial-outflow | official-inflow | official-outflow | private-inflow | private-outflow |
|----|------|-------------------|--------------------|-----------------|------------------|----------------|-----------------|
| AF | 2000 | 1.5 | 2.5 | 15.2 | 1.1 | 11.5 | 17.3 |

That way, we can avoid the messy topic of classifying countries as donors or recipients, and just graph inflows vs. outflows. If the "inflow" categories are blank, the country-profile could automatically skip it and draw the next vis.

P.S. If you don't already have a starting point for that radial-treemap, I found an example on mbostock's page that could serve as inspiration: http://www.jasondavies.com/coffee-wheel/ If MongoDB can return hierarchical JSON like the file used to power this one (http://www.jasondavies.com/coffee-wheel/wheel.json), that might also be a smart way to organize the data.

**Comment by akmiller01** [comment]
I think @robtew had the most insight on how this should be organized. It gets quite complicated, and we probably do need to divide donors from recipients somehow in order to make sense of contributions to and from multilats.

**Comment by robtew** [comment]
I suggested that we add a 'entity type' column to the entity file.  This could have 4 values: bilateral donor, multilateral body, recipient and crossover (i.e. both a recipient and a donor).  I could go through the file and add this pretty quickly if others think it a good idea.

**Comment by dw8547** [comment]
Dead issue.
