### ISSUE TITLE
Human readable IDs in entity.csv?

### ISSUE THREAD

**Issue by lapidus** [devinit/digital-platform#49]
Can organisations and regional entities also get human readable/string-like IDs or would that mess up the work/relationships to DAC data etc?
https://github.com/devinit/digital-platform/blob/master/reference/entity.csv

We can work with what we have but if there's a batch script that can give us something more friendly then the numerical IDs it may be helpful

One reason this is helpful is that we use the IDs for, for example, CSS styling in the application. Now we have to do something like:

```
.region-89  { background:lighten(@color-purple, 20%); } // Europe
.region-189 { background:@color-green;                } // Africa (North of Sahara)
.region-289 { background:@color-red;                  } // Africa (South of Sahara)
```

Where we could have:

```
.region-europe  { background:lighten(@color-purple, 20%); }
```

**Comment by akmiller01** [comment]
This makes sense to me. We already have "type" to distinguish between organisations and countries, we don't need their IDs to be styled differently as well. I'm not sure if it would change the relationship to any other datasets, but perhaps a solution would be renaming the current ID something else (E.g. "dac-id").

**Comment by bill-anderson** [comment]
Yup, I have no objection to this so long as the relationship between dac-id and the new id is maintained  somewhere. @akmiller01 do you have time to do this today?

**Comment by akmiller01** [comment]
Working on it now.

**Comment by akmiller01** [comment]
https://github.com/devinit/digital-platform/commit/ca2da0acd13fab7b6790ebbae8e26f9f6d2d3598
