### ISSUE TITLE
Multi or composite files?

### ISSUE THREAD

**Issue by timstrawson** [devinit/digital-platform#50]
@lapidus I'm working on the master files for a few resource flows (long-term loans, fdi, dfis etc.) for the country profiles and I'm not sure whether to structure them as multi or composite files. Could you advise? I'll email you the hierarchy for the loans data in the first instance.

**Comment by lapidus** [comment]
Thanks Tim, yes please send/post examples and any questions. @bill-anderson and @akmiller01 may have opinions here as well.

**Comment by lapidus** [comment]
Tim posted: Here’s the loans data hierarchy as mentioned just now in the issues log. Great if you could advise whether this is better as a multi or a composite structure. Eg in the multi structure the column headings would be the following:
 
id_to
Flow
Destination_institution_type
Source_institution_type_1
Source_institution_type_2
Financing_type
Institution
value

![image](https://cloud.githubusercontent.com/assets/66601/6185586/6f26bfaa-b370-11e4-9f06-5710e76b4b0a.png)

**Comment by timstrawson** [comment]
Ok, I've just added the file in multi format as well as new reference files + updated concepts file - @akmiller01 or @bill-anderson  - grateful if you were able to cast your eye over them as there are quite a few parts to it all and I want to make sure I've structured & linked it all up correctly
Note that for now this is just 2013 data - once Dan W is back on Monday we will update the long_term_debt file with data from previous years

**Comment by akmiller01** [comment]
Thanks, Tim. There's just a few formatting pieces I need to fix (removing caps, replacing underscores with dashes). I'll fix those now.

**Comment by timstrawson** [comment]
Thanks @akmiller01 , though actually would you be able to fix them in the underlying file on our s drive? We'll need to re-upload the data once Dan's back and has added the data for earlier years to the file as well. If you fix these issues on the s drive we won't need to amend again once we've re-uploaded it. I'll send you the link over email.

**Comment by dw8547** [comment]
Dead issue.
