### ISSUE TITLE
Repo coverage of world map visualisation datasets?

### ISSUE THREAD

**Issue by lapidus** [devinit/digital-platform#51]
@bill-anderson, @akmiller01: What approx. coverage do we have for these in the repo currently? (I think it would be very useful to have all these as "singles".)

*DI word doc. on list of indicators for map visualizations*:

![image](https://cloud.githubusercontent.com/assets/66601/6208102/ed34630e-b5b2-11e4-90e2-e9cf8ce3f33d.png)
![image](https://cloud.githubusercontent.com/assets/66601/6208106/ffa7e574-b5b2-11e4-93c4-96ac9cb1016b.png)

**Comment by akmiller01** [comment]
| theme | indicator | in-repo | single-value | notes |
|--------------------------------|----------------------------------------------------------------------------|---------|--------------|-------------------------------------------------------------------------------------|
| Poorest 20% of People | Number of people who are part of the global poorest 20% in each country | TRUE | TRUE | poorest20% |
| Poorest 20% of People | Number of people in the global poorest 20% living on less than $1.25 a day | TRUE | TRUE | poverty-125 |
| Poorest 20% of People | Percent of people who are part of the global poorest 20% in each country | TRUE | TRUE | poorest20%-percentages |
| Poorest 20% of People | Average income of people living on less than $1.25 | TRUE | TRUE | avg-income-of-extreme-poor |
| Domestic Public Finance | Gov't spending per person | TRUE | TRUE | govtspend-pc |
| Domestic Public Finance | Government revenue (excluding grants) % GDP | FALSE | FALSE | Only tax-revenue % GDP in repo |
| Domestic Public Finance | Gov't spending % GDP | TRUE | FALSE | Needs calculation from govtspend-USD and gdp-usd-current |
| Domestic Public Finance | External grants as proportion of total revenue | FALSE | FALSE |  |
| Mix of International Resources | Largest resource received by each country | TRUE | FALSE | Maybe in repo, but needs calculating from all the bundle csvs |
| Mix of International Resources | FDI per person | TRUE | FALSE | Needs calculation from di-only/country-year/in-fdi and population-total |
| Mix of International Resources | Profit outflows as proportion of FDI | FALSE | FALSE | Maybe di-only/country-year/in-fdi-profits or di-only/country-year/from-fdi-profits? |
| Mix of International Resources | Remittances per person | TRUE | FALSE | Needs calculation from di-only/country-year/in-remittances and pop |
| Int'l Public Finance | Gross ODA receipts | TRUE | TRUE | di-only/country-year/in-oda-gross |
| Int'l Public Finance | ODA per poor person | TRUE | TRUE | di-only/country-year/oda-per-poor-person |
| Int'l Public Finance | Gross OOFs receipts | TRUE | TRUE | di-only/country-year/in-oof-gross |
| Int'l Public Finance | OOFs per poor person | TRUE | FALSE | Needs calc |
| Int'l Public Finance | net OOFs provided | TRUE | TRUE | di-only/country-year/out-oof-gross |
| Int'l Public Finance | net ODA provided | TRUE | TRUE | di-only/country-year/out-oda-gross |
| Int'l Public Finance | ODA %GNI | TRUE | FALSE | Needs calc |
| Int'l Public Finance | ODA to LDCs % GNI | TRUE | FALSE | Needs calc |
| Int'l Public Finance | ODA % total public spending | TRUE | FALSE | Needs calc |
| Humanitarian Finance | Total receipts | TRUE | TRUE | di-only/country-year/in_ha |
| Humanitarian Finance | % of ODA | TRUE | FALSE | Needs calc |
| Humanitarian Finance | Spending as a proprotion of UN appeals | FALSE | FALSE | http://fts.unocha.org/pageloader.aspx?page=searchproject-customsearch |
| Humanitarian Finance | Receipt of long-term humanitiarian assistance | FALSE | FALSE |  |
| Humanitarian Finance | Total assistance | TRUE | TRUE | Is this different from "Total receipts""?" |
| Humanitarian Finance | % of ODA | TRUE | FALSE | Needs calc |
| Vulnerability | Climate Change (GAIN index) | FALSE | FALSE |  |
| Vulnerability | Fragile states group (Fund for Peace) | FALSE | FALSE |  |
| Vulnerability | Natural Hazard exposure score (INFORM) | FALSE | FALSE |  |
| Vulnerability | Human hazard exposure score (conflict) (INFORM) | FALSE | FALSE |  |

**Comment by akmiller01** [comment]
Also, the word "coverage" had me thinking about the missing data in the repository. Here's a real quick spatial-join look at the countries we have data for for Number of people living under $1.25 per day in 2000. Out of 213 countries, only 47 have data. 3 of those countries' IDs didn't match with what I have for ISO-2s, but here's what 44 of them look like on a map:
![pov-125-2000-coverage](https://cloud.githubusercontent.com/assets/2836840/6211437/ba02068e-b5d1-11e4-9188-0477b33d5617.png)

We probably need to think about how to represent missing data.

**Comment by akmiller01** [comment]
Here's all countries with at least one data-point from 2000 to 2013:
![pov-125-at-least-one-year-coverage](https://cloud.githubusercontent.com/assets/2836840/6211833/302f9606-b5d6-11e4-9a66-4526dd9571d1.png)

**Comment by timstrawson** [comment]
@akmiller01 @bill-anderson would it be possible to add all the outstanding files under this milestone as separate issues? some of those in alex's list above have since been added and it'd be useful to list separately so we can keep track of them all

**Comment by akmiller01** [comment]
Hey @timstrawson , I think they're already actually issues. All the issues starting with "Country-Profile" were taken straight from that spreadsheet.

**Comment by timstrawson** [comment]
Ah ok, great, thanks.
