### ISSUE TITLE
Country profiles: mix of international resources

### ISSUE THREAD

**Issue by akmiller01** [devinit/digital-platform#55]
![image](https://cloud.githubusercontent.com/assets/2836840/6249161/3f4d526a-b77d-11e4-8e01-dc2323b077b0.png)

**Comment by timstrawson** [comment]
- added rems-pp for remittances per person

**Comment by timstrawson** [comment]
added fdi-pp

**Comment by timstrawson** [comment]
added profits-pct-fdi

**Comment by dw8547** [comment]
Dead or a non issue.
