### ISSUE TITLE
Country-Profile: Humanitarian Finance

### ISSUE THREAD

**Issue by akmiller01** [devinit/digital-platform#57]
![image](https://cloud.githubusercontent.com/assets/2836840/6249213/a21a1158-b77d-11e4-95e2-a8a91febf792.png)

**Comment by akmiller01** [comment]
Can't assign two people, so I'll tag @timstrawson here too if you decide to take it.

**Comment by timstrawson** [comment]
added in-ha for total receipts (including ODA)
