### ISSUE TITLE
Country-Profile: Vulnerability

### ISSUE THREAD

**Issue by akmiller01** [devinit/digital-platform#58]
![image](https://cloud.githubusercontent.com/assets/2836840/6249239/c65bd8c6-b77d-11e4-8d15-37403da53c25.png)

**Comment by timstrawson** [comment]
I've added files for lines 1, 3 and 4 in the table above. I'll add the fragile states groupings tomorrow morning. Note that I need to confirm the year of the natural and human hazard indices, and confirm whether historic data are available - I will confirm with Anna once she is back next week

**Comment by timstrawson** [comment]
added the one remaining file: fragile-states
