### ISSUE TITLE
long_term_debt issues

### ISSUE THREAD

**Issue by lapidus** [devinit/digital-platform#59]
A couple of issues with "long-term-debt" it seems:

1. In concepts.csv it features underscores: long_term_debt 

2. The csv file has a number of "#VALUE" items. Also, should there be 0s in there or blank cells?
https://github.com/devinit/digital-platform/blob/master/country-year/long-term-debt.csv

**Comment by akmiller01** [comment]
@robtew , do we have the original excel spreadsheet these were made from? We need to check to make sure #VALUE should be blank, and is not just a formula error.

**Comment by timstrawson** [comment]
@lapidus @akmiller01 I've amended the original files - the #VALUE cells for Syria now read 'NA'. I've also amended the hyphens. There are no blank cells - all are now either 'NA' or 0 for absolute zero observations.
