### ISSUE TITLE
Issues with % files

### ISSUE THREAD

**Issue by lapidus** [devinit/digital-platform#60]
Please rename all files with %-signs in the file name as they are causing some problems for the API:

https://github.com/devinit/digital-platform/blob/master/country-year/taxrev-%25GDP.csv
https://github.com/devinit/digital-platform/blob/master/country-year/poorest20%25-percentages.csv
https://github.com/devinit/digital-platform/blob/master/country-year/poorest20%25.csv

Also, these files have issues such as:
- values given with "%" sign
- values given as "No Data"

Overall, great if we can minimize these kinds of issues in the "public part" of the repo is at may cause all sorts of issues when we import and visualize ;) Thanks!

**Comment by akmiller01** [comment]
Done.
